courses/urls.py
from django.urls import path
from .views import courses_list,coursesdetail,productlist,courses_detail
from . import views
app_name ='courses'
urlpatterns = [
    
    path('', courses_list, name='home-page'),
    path('<int:id>/', views.courses_detail, name='course_detail'),    
    ]

project/urls.py
from django.contrib import admin
from django.urls import path , include 
from django.conf.urls.static import static 
from django.conf import settings 


urlpatterns = [
    path("accounts/", include("django.contrib.auth.urls")),
    path ("accounts/", include('accounts.urls',namespace='accounts')),
    path('admin/', admin.site.urls),
    path ("courses/", include('courses.urls',namespace='courses')),
]
if settings.DEBUG:
  urlpatterns +=static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
  urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

courses/models.py
from django.db import models

# Create your models here.
from django.utils.translation import gettext as _ # type: ignore
from django.contrib.auth.models import User # type: ignore
# Create your models here.


class Section(models.Model):
    name = models.CharField(max_length=100)

    def __str__(self):
        return self.name

class courses(models.Model):
    rodmapimage=models.ImageField(_("rodmapimage"), upload_to='rodmap_image')
    section = models.ForeignKey(Section, related_name='courses',verbose_name="section", on_delete=models.CASCADE)
    is_paid = models.BooleanField(default=True)
    image=models.ImageField(_("image"),upload_to='courses_image')
    name=models.CharField(_("name"),max_length=50)
    rate=models.IntegerField(verbose_name="rate")
    doctorname=models.ForeignKey('course_content',verbose_name="doctor_name", on_delete=models.CASCADE)

    def __str__(self):
        return self.name
    
class course_content(models.Model):
    doctorname=models.CharField(_("doctor_name"), max_length=60)
    department=models.CharField(_("Department"), max_length=50)
    subtitel=models.TextField(_("about"),max_length=300,null=True,blank=True)
    subtitell=models.TextField(_("doc"),max_length=300,null=True,blank=True)
    vediourl=models.URLField(null=True,blank=True)
    urlcourses=models.URLField(null=True)
    image = models.ImageField(_("userimage"),upload_to='doctor_image' ,default="midia/doc.jpeg" )
    def __str__(self):
        return self.doctorname

courses/views.py
from django.shortcuts import render,get_object_or_404
from django.views.generic import ListView ,DetailView
from .models import Section , courses,course_content
# Create your views here.
class productlist(ListView):
    model = courses
class coursesdetail(DetailView):
    model = courses
    
def courses_list(request):
    sections = Section.objects.all()
    return render(request, 'courses/courses_list.html', {'sections': sections})




def courses_detail(request, id):
    courses_detail =course_content.objects.get(id=id) 
    return render(request, 'courses/course_detail.html', {'course': courses_detail})

courses/templates/courses/course_detail.html
{% extends "hader-fotar.html" %}
{% block bady %}


</section> 
<section class="text-box">
  <div class="container1">
    <h1> </h1>
    {% if course.videourl %}
    <!-- <p><iframe controls width="1000" height="700" src="{{ course.vediourl }}" frameborder="0" allowfullscreen></iframe> -->
      <p><video width="1000" height="700" controls>
      <source src="{{course.vediourl}}" type="video/mp4">
    </video> 
    {% else %}
    <p>No video available.</p>
    {% endif %}

    <!--
    </p>
    <a href="" class="hero-btn"> To know More courses </a>
  --></div>
  </section>
        <!-- <iframe controls width="1000" height="700" src="{{ course.vediourl }}" frameborder="0" allowfullscreen></iframe> -->

 
    <main id="overview">
  <b><h5 class="title" >OVERVIEW</h5></b> 
  <div class="main-title   position-relative">
    
</div>
  <hr class="separator">
  <div class="article">
    <h2>About this course</h2>
    <p> {{course.subtitel}} m</p>

  <hr class="separator">
  <div class="article">
    <div class="avatar avatar-lg rounded">
        <img src="{{course.image.url}}" title="" alt="">
  </div>
    <h2>{{course.doctorname}}</h2>
    <h4>{{course.department}}</h4>
    <p>{{course.subtitell}}</p>
  </div>
  <hr class="separator">
  <div class="article">
    <h2>Course  Link</h2>
<p><b><li><a href=" {{course.urlcourses}}">{{course.urlcourses}}</a></li></b></p>
</div>
</main>
{% endblock bady %}

courses/templates/courses/courses_list..html
{% extends "hader-fotar.html" %}
{% load static %}
{% block bady %}
{% block myhome %}
<link rel="stylesheet" href="{% static 'css/home.css' %}">
<script src="{% static 'js/script.js' %}"defer></script>
{% endblock myhome %}
    <section>
        <div class="container">
            <div class="slider-wrapper">
              <button id="prev-slide" class="slide-button material-icons">
                chevron_left
              </button>
              <ul class="image-list">
                <img class="image-item" src=" {% static 'images/1.png' %}" alt="img-1" />
                <img class="image-item" src="{% static 'images/1.png' %}"  alt="img-2" />
                <img class="image-item" src="{% static 'images/1.png' %}" alt="img-3" />
                <img class="image-item" src="{% static 'images/1.png' %}" alt="img-4" />
                <img class="image-item" src="{% static 'images/1.png' %}" alt="img-5" />
                <img class="image-item" src="{% static 'images/1.png' %}" alt="img-6" />
                <img class="image-item" src="{% static 'images/1.png' %}" alt="img-7" />
                <img class="image-item" src="{% static 'images/1.png' %}" alt="img-8" />
                <img class="image-item" src="{% static 'images/1.png' %}" alt="img-9" />
                <img class="image-item" src="{% static 'images/1.png' %}" alt="img-10" />
              </ul>
              <button id="next-slide" class="slide-button material-icons">
                chevron_right
              </button>
            </div>
            <div class="slider-scrollbar">
              <div class="scrollbar-track">
                <div class="scrollbar-thumb"></div>
              </div>
            </div>
          </div>     
    </section>


    <section>

    
        <div class="content-area">
            <h1>Courses List</h1>
            <h3>Paid Courses</h3>
            {% for section in sections %} 
            <ul>
                {% for courses in section.courses.all %}
                    {% if  courses.is_paid %}
                    <h2 class="title">{{ section.name }}</h2>
                    
                    <main>
                        <div class="videos-container">
                            <div class="video">
                                <div class="thumbnail"> 
                                    <img src="{{courses.image.url}}" />
                                </div>
                                <div class="video-detils">
                          
                                    <div class="title">
                                        <a href="{%url 'courses:course_detail' courses.id %}" class="video-title">
                                            {{courses.name}}
    
                                        </a>
                                        <a href="{%url 'courses:course_detail' courses.id %}" class="video-creator">
                                            {{ courses.doctorname }}
    
                                         </a>
                                        <div class="cotn">
                                            
                                            <span text=bold >{{ courses.rate }}</span>
                                            <span class="fa fa-star fa-x checked"></span>
                                            
                                        </div>
                                    </div>
                                </div>
                            </div> 
                        </div> 
                    </main>
                    {% endif %}
                {% endfor %}
            </ul> 
            <h3>Free Courses</h3>
            <ul>
                {% for courses in section.courses.all %}
                    {% if not courses.is_paid %}
                    <h2 class="title">{{ section.name }}</h2>
                    <main>
                        <div class="videos-container">
                            <div class="video">
                                <div class="thumbnail"> 
                                    <img src="{{courses.image.url}}" />
                                </div>
                        
                                <div class="video-detils">
                          
                                    <div class="title">
                                        <a href="{%url 'courses:course_detail' courses.id %}" class="video-title">
                                            {{ courses.name}}
    
                                        </a>
                                        <a href="{%url 'courses:course_detail' courses.id %}" class="video-creator">
                                            {{ courses.doctorname}}
    
                                         </a>
                                        <div class="cotn">
                                            <span text=bold >{{ courses.rate }}</span>
                                            <span class="fa fa-star fa-x checked"></span>
                                        </div>
                                    </div>
                                </div>
                            </div>  
                        </div> 
                    </main>
                    {% endif %}
                {% endfor %}
            </ul> 
            {% endfor %}
           
        </div>
    

   
    </section>

   


{% endblock bady %}

courses/templates/courses/courses_list.html
{% extends "hader-fotar.html" %}
{% load static %}
{% block bady %}
{% block myhome %}
<link rel="stylesheet" href="{% static 'css/home.css' %}">
<script src="{% static 'js/script.js' %}"defer></script>
{% endblock myhome %}
    <section>
        <div class="container">
            <div class="slider-wrapper">
              <button id="prev-slide" class="slide-button material-icons">
                chevron_left
              </button>
              <ul class="image-list">
                <img class="image-item" src=" {% static 'images/1.png' %}" alt="img-1" />
                <img class="image-item" src="{% static 'images/2.jpg' %}"  alt="img-2" />
                <img class="image-item" src="{% static 'images/3.jpg' %}" alt="img-3" />
                <img class="image-item" src="{% static 'images/4.jpg' %}" alt="img-4" />
                <img class="image-item" src="{% static 'images/5.jpg' %}" alt="img-5" />
                <img class="image-item" src="{% static 'images/1.png' %}" alt="img-6" />
                <img class="image-item" src="{% static 'images/2.jpg' %}" alt="img-7" />
                <img class="image-item" src="{% static 'images/3.jpg' %}" alt="img-8" />
                <img class="image-item" src="{% static 'images/4.jpg' %}" alt="img-9" />
                <img class="image-item" src="{% static 'images/5.jpg' %}" alt="img-10" />
              </ul>
              <button id="next-slide" class="slide-button material-icons">
                chevron_right
              </button>
            </div>
            <div class="slider-scrollbar">
              <div class="scrollbar-track">
                <div class="scrollbar-thumb"></div>
              </div>
            </div>
          </div>     
    </section>


    <section>

    
        <div class="content-area">
            <h3>Paid Courses</h3>
            {% for section in sections %} 
            <ul>
                {% for courses in section.courses.all %}
                    {% if  courses.is_paid %}
                    <h2 class="title">{{ section.name }}</h2>
                    
                    <main>
                        <div class="videos-container">
                            <div class="video">
                                <div class="thumbnail"> 
                                    <img src="{{courses.image.url}}" />
                                </div>
                                <div class="video-detils">
                          
                                    <div class="title">
                                        <a href="{%url 'courses:course_detail' courses.id %}" class="video-title">
                                            {{courses.name}}
    
                                        </a>
                                        <a href="{%url 'courses:course_detail' courses.id %}" class="video-creator">
                                            {{ courses.doctorname }}
    
                                         </a>
                                        <div class="cotn">
                                            
                                            <span text=bold >{{ courses.rate }}</span>
                                            <span class="fa fa-star fa-x checked"></span>
                                            
                                        </div>
                                    </div>
                                </div>
                            </div> 
                        </div> 
                    </main>
                    {% endif %}
                {% endfor %}
            </ul> 
            <h3>Free Courses</h3>
            <ul>
                {% for courses in section.courses.all %}
                    {% if not courses.is_paid %}
                    <h2 class="title">{{ section.name }}</h2>
                    <main>
                        <div class="videos-container">
                            <div class="video">
                                <div class="thumbnail"> 
                                    <img src="{{courses.image.url}}" />
                                </div>
                        
                                <div class="video-detils">
                          
                                    <div class="title">
                                        <a href="{%url 'courses:course_detail' courses.id %}" class="video-title">
                                            {{ courses.name}}
    
                                        </a>
                                        <a href="{%url 'courses:course_detail' courses.id %}" class="video-creator">
                                            {{ courses.doctorname}}
    
                                         </a>
                                        <div class="cotn">
                                            <span text=bold >{{ courses.rate }}</span>
                                            <span class="fa fa-star fa-x checked"></span>
                                        </div>
                                    </div>
                                </div>
                            </div>  
                        </div> 
                    </main>
                    {% endif %}
                {% endfor %}
            </ul> 
            {% endfor %}
           
        </div>
    

   
    </section>

   


{% endblock bady %}